### ISSUE TITLE
Statistics tab not displayed on post preview if debug mode is enabled.

### ISSUE THREAD

**Issue by AliaksandrVahura-ScienceSoft** [laterpay/laterpay-wordpress-plugin#556] opened 2015-01-20 16:46 UTC
Statistics ajax request contain next notices:
<b>Notice</b>:  WP_Date_Query was called <strong>incorrectly</strong>. Invalid value <code>0</code> for <code>hour</code>. Expected value should be between <code>1</code> and <code>23</code>. Please see <a href="http://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 4.1.0.) in <b>/srv/www/wordpress-default/wp-includes/functions.php</b> on line <b>3547</b>

**Comment by Chrico** [comment] 2015-01-20 16:54
This just appears when WordPress is in `WP_DEBUG_DISPLAY`-Mode and is caused by a WordPress-Bug. This will be fixed with 4.1.1, see more informations here: https://core.trac.wordpress.org/ticket/31067

**Comment by drdla** [comment] 2015-02-20 07:02
ok, so WordPress 4.1.1 is out now. Do we have to do anything now @Chrico or will it automatically work again?

**Comment by Chrico** [comment] 2015-02-20 08:08
nope everything fine. this error just exists for WP < 4.1.1.

**Comment by twoldrich** [comment] 2015-02-24 16:53
Works fine with active / disables debug mode.

**Closed by twoldrich** 2015-02-24 16:53 UTC
Labels: Conflict
