### ISSUE TITLE
Duplicate purchase required

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#469] opened 2014-11-18 18:51 UTC
After purchasing a post with activated page cache, I still saw the protected page and had to click the purchase button a second time. The plugin correctly recognized that I had already bought that post and forwarded me to the content with a flash message.

**Comment by drdla** [comment] 2015-01-22 18:01
Dunno if this is still happening

**Comment by twoldrich** [comment] 2015-02-03 10:16
With the current master, I still have to purchase twice with an active caching plugin: After confirming the purchase dialog, the flash message ("Enjoy your purchase") isn't closed automatically.

So to access the purchase I can either
- **Close** the flash message and **reload** the page or
- **Close** the flash message and **click the purchase button again**.

Without caching plugin, everything works fine.

**Comment by twoldrich** [comment] 2015-08-11 10:50
I cannot reproduce this anymore and as we didn't receive any support requests for this issue, I will close it.

**Closed by twoldrich** 2015-08-11 10:50 UTC
Labels: Bug (critical)
