### ISSUE TITLE
PHP Notices after WP Update to 4.2.4. / slow page load in sandbox mode (edited: more precise title)

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#817] opened 2015-08-05 16:03 UTC
```
PHP Notice:  Trying to get property of non-object in /wp-includes/query.php on line 4373
PHP   1. {main}() /index.php:0
PHP   2. require() /index.php:17
() /wp-includes/plugin.php:269
```

I get that several times per request of the homepage. And I get that notices each time, when I request the same page when the laterpay plugin is active.

I do not get the notices when I disable the laterpay plugin.

I did not get the notices when laterpay plugin is active and I use WP 4.2.3.

**Comment by twoldrich** [comment] 2015-08-11 10:08
@mturalenka Could you please have a look or reassign the ticket if necessary?

**Comment by twoldrich** [comment] 2015-08-11 10:08
@larsschenk And of course thanks for reporting this! :)

**Comment by AliaksandrVahura-ScienceSoft** [comment] 2015-08-11 11:17
@twoldrich @mturalenka Can't reproduce this issue on my env. Can you try to reproduce it also, please?

**Comment by larsschenk** [comment] 2015-08-11 11:48
Additional infos: I have the same symptoms in sandbox mode and in live mode. I have it on two different setups. First is my local devo mashine and second is my testing/staging setup on heroku. 

I get:

PHP Notice:  Trying to get property of non-object in /app/wp-includes/query.php on line 4375
PHP Notice:  Trying to get property of non-object in /app/wp-includes/query.php on line 4377
PHP Notice:  Trying to get property of non-object in /app/wp-includes/query.php on line 4373

in the logs. And the homepage (and maybe others, too) is loading very slow.

I get rid of slow homepage loading and the PHP Notices, when I deactivate the plugin.
Local setup and heroku staging do not use the same database.

**Comment by mturalenka** [comment] 2015-08-11 12:10
@larsschenk thank you for the information, we will try to reproduce PHP notices, 
could you please share more info about your env, php version, modules installed, mysql version?

slow page loading looks like is not related to php notices. we figured that one of the JS used both in sandbox and live mode blocks page loading. we will try to resolve this asap

**Comment by larsschenk** [comment] 2015-08-11 12:40
Laterpay Plugin Version 0.9.12 

local dev:
homebrew/php/php56: stable 5.6.11, built from source with: --homebrew-apxs. 
mysql: stable 5.6.25 (bottled)

heroku staging:
It is pretty stock setup (using official buildpack with vendor/bin/heroku-php-nginx)
PHP Version 5.6.11
mysql: 5.5.40-log
with additional add ons (that I think should not disturb the laterpay plugin):
memcached 2.2.0, ibmemcached version 1.0.18 and SASL support enabled.
New Relic Version 4.23.1.107 ("hydrobatidae" - "8853b158862b028753eb72f37a274c68b5cfb76c")

Let me know if you want to know any specific that I might have missed to list (maybe a list of installed plugins might be helpful?)

And keep in mind that the PHP notices have been seen in the logs only after/with the WordPress 4.2.4 update. (A downgrade for testing purpose solved that issue).

**Comment by mturalenka** [comment] 2015-08-11 12:47
@larsschenk thanks for the information, js loading in live mode seems has been already fixed, could you please confirm, that live mode is ok?
sandbox still in progress

**Comment by larsschenk** [comment] 2015-08-11 13:09
Thanks @mturalenka : I can confirm now that live mode has been already fixed. 
I needed to flush my page cache to get the positive result after changing from sandbox to live mode; sorry for my false report regarding slow page load. It's only an issue in sandbox mode.

The above reported PHP notices are still there - when the home page does not load from the cache.
But I assume now it's just a minor problem (notices != errors) because I do not have any other signs for a real problem here.

**Comment by AliaksandrVahura-ScienceSoft** [comment] 2015-08-13 08:21
@larsschenk Finally reproduced this issue. These notices appeared on the home page when we use static page as front page (in menu "reading" select static page as front page).

**Comment by AliaksandrVahura-ScienceSoft** [comment] 2015-08-13 09:02
@mturalenka Slow page load on sandbox env can't be fixed by me. Please review and close if all ok.

**Comment by AliaksandrVahura-ScienceSoft** [comment] 2015-08-13 09:13
@mturalenka Just checked yui config availability and it's available for sandbox as well. So slow work should be fixed as well. @larsschenk Please check.

**Closed** 2015-08-13 11:08 UTC
